# Apply handcrafted composition-module counterexample/instance patches
$ErrorActionPreference = 'Stop'
$OrchRoot = (Join-Path $PSScriptRoot "..\ontology\orchestration-plane") | Resolve-Path

function Insert-Examples {
    param([string]$RelPath, [string]$Block)
    $full = Join-Path $OrchRoot $RelPath
    $content = Get-Content $full -Raw -Encoding UTF8
    foreach ($key in @('parent_relation', 'sources', 'source_claims')) {
        if ($content -match "(?m)^$key`:") {
            $content = [regex]::Replace($content, "(?m)^$key`:", ($Block.TrimEnd() + "`r`n$key`:"), 1)
            Set-Content -Path $full -Value $content -Encoding UTF8 -NoNewline
            Write-Host "OK $RelPath"
            return
        }
    }
    throw "No anchor in $RelPath"
}

$p = @{
"orchestration-composition/CompositionArtifact/CompositionOutput/node.yaml" = @'
  - id: CompositionOutput-counterexample-synthesis-input
    kind: counterexample
    labels: { zh: 综合输入不是组合输出, en: Synthesis input is not composition output, ja: synthesis input は composition output ではない }
    scenario_id: null
    descriptions:
      zh: synthesis-input-12 列出三节草稿引用供综合消费，但没有 output_role、content_digest 或 produced_at 所证明的已生成输出身份。
      en: synthesis-input-12 lists three draft refs for synthesis consumption but lacks output_role, content_digest, or produced_at proving generated output identity.
      ja: synthesis-input-12 は三 draft ref を列挙しますが output_role/content_digest/produced_at による generated output identity がありません。
    field_values: { output_role: absent, content_digest: absent, produced_at: absent, input_refs: [draft-a, draft-b, draft-c] }
    related_node_ids: [CompositionOutput, SynthesisInput, CompositionArtifact]
    related_relation_ids: []
    expected_result: { zh: 拒绝 CompositionOutput 分类；保留为 SynthesisInput 消费侧引用集合。, en: Reject CompositionOutput; retain as SynthesisInput consumer reference set., ja: CompositionOutput 分類を拒否し SynthesisInput consumer ref set として保持。 }
    why_valid_or_invalid:
      zh: 组合输出是 Activity 生成的不可变结果实体；待综合的输入引用集合属于上游输入而非输出。
      en: Composition output is an immutable result entity generated by activity; input refs awaiting synthesis are upstream inputs, not outputs.
      ja: composition output は activity 生成 immutable result entity であり synthesis 待ち input ref は upstream input です。
    synthetic: true
    verified_version: null
    source_claims: [claim-composition-output-002]
'@

"orchestration-composition/CompositionArtifact/CompositionOutput/SynthesisOutput/node.yaml" = @'
  - id: SynthesisOutput-counterexample-merge-activity
    kind: counterexample
    labels: { zh: 合并活动不是综合输出, en: Merge activity is not synthesis output, ja: merge activity は synthesis output ではない }
    scenario_id: null
    descriptions:
      zh: merge-run-52 在 10:31–10:32 执行章节拼接并有 status=running，但没有 synthesis_output_id 或 final_content_digest 固定的综合结果实体。
      en: merge-run-52 executes section stitching from 10:31–10:32 with status=running but lacks synthesis_output_id or final_content_digest fixing a synthesis result entity.
      ja: merge-run-52 は section stitching を実行しますが synthesis_output_id/final_content_digest がありません。
    field_values: { synthesis_output_id: absent, final_content_digest: absent, activity_status: running }
    related_node_ids: [SynthesisOutput, Synthesis, CompositionActivity]
    related_relation_ids: []
    expected_result: { zh: 拒绝 SynthesisOutput 分类；保留为 CompositionActivity 运行时合并。, en: Reject SynthesisOutput; retain as CompositionActivity runtime merge., ja: SynthesisOutput 分類を拒否。 }
    why_valid_or_invalid:
      zh: 综合输出记录最终合成内容的不可变身份；时间跨度的合并活动是 PROV Activity 而非 Entity。
      en: Synthesis output records immutable identity of final synthesized content; time-bounded merge is PROV Activity not Entity.
      ja: synthesis output は final synthesized content の immutable identity を記録し time-bounded merge は Activity です。
    synthetic: true
    verified_version: null
    source_claims: [claim-synthesis-output-002]
'@

"orchestration-composition/CompositionArtifact/SynthesisInput/node.yaml" = @'
  - id: SynthesisInput-counterexample-synthesis-output
    kind: counterexample
    labels: { zh: 综合输出不是综合输入, en: Synthesis output is not synthesis input, ja: synthesis output は synthesis input ではない }
    scenario_id: null
    descriptions:
      zh: artifact-final-report 含 sha256:final-report 与 produced_at，是综合活动产出的结果，却被误标为 synthesis-input。
      en: artifact-final-report carries sha256:final-report and produced_at as synthesis activity result but is mislabeled synthesis-input.
      ja: artifact-final-report は sha256:final-report/produced_at を持つ synthesis 結果ですが synthesis-input と誤ラベルされています。
    field_values: { synthesis_input_id: absent, source_artifact_refs: absent, content_digest: sha256:final-report, produced_at: 2026-07-16T04:22:00Z }
    related_node_ids: [SynthesisInput, SynthesisOutput, CompositionArtifact]
    related_relation_ids: []
    expected_result: { zh: 拒绝 SynthesisInput 分类；分类为 SynthesisOutput 或 CompositionOutput。, en: Reject SynthesisInput; classify as SynthesisOutput or CompositionOutput., ja: SynthesisInput 分類を拒否。 }
    why_valid_or_invalid:
      zh: 综合输入引用待合并的上游草稿；已生成 digest 与 produced_at 证明它是输出实体而非输入引用集合。
      en: Synthesis input references upstream drafts to merge; existing digest and produced_at prove an output entity not an input reference set.
      ja: synthesis input は upstream draft を参照し digest/produced_at は output entity を証明します。
    synthetic: true
    verified_version: null
    source_claims: [claim-synthesis-input-002]
'@

"orchestration-composition/CompositionSpecification/CompositionPattern/Parallelization/node.yaml" = @'
  - id: Parallelization-counterexample-parallel-activity-run
    kind: counterexample
    labels: { zh: 并行运行活动不是并行化模式, en: Parallel run activity is not parallelization pattern, ja: parallel run activity は parallelization pattern ではない }
    scenario_id: null
    descriptions:
      zh: parallel-run-884 在 04:20 同时启动三个 LangGraph 分支线程并有 started_at，但没有 branch_refs 或 independence_condition 声明的可复用 fan-out/fan-in 模式。
      en: parallel-run-884 launches three LangGraph branch threads at 04:20 with started_at but lacks branch_refs or independence_condition declaring a reusable fan-out/fan-in pattern.
      ja: parallel-run-884 は 04:20 に三分岐を起動しますが branch_refs/independence_condition がありません。
    field_values: { composition_specification_id: absent, branch_refs: absent, independence_condition: absent, started_at: 2026-07-16T04:20:00Z }
    related_node_ids: [Parallelization, CompositionActivity, ParallelBranch]
    related_relation_ids: []
    expected_result: { zh: 拒绝 Parallelization 分类；保留为 CompositionActivity 并行执行。, en: Reject Parallelization; retain as CompositionActivity parallel execution., ja: Parallelization 分類を拒否。 }
    why_valid_or_invalid:
      zh: 并行化模式声明分支独立条件与 join 策略而不含调度发生时间；运行时重叠不能替代语义独立判断。
      en: Parallelization pattern declares branch independence and join policy without scheduler occurrence time; runtime overlap cannot substitute semantic independence.
      ja: parallelization pattern は branch independence/join policy を宣言し occurrence time を含みません。
    synthetic: true
    verified_version: null
    source_claims: [claim-parallelization-001]
  - id: Parallelization-instance-independent-source-review
    kind: instance
    labels: { zh: 三来源独立审查并行化实例, en: Three-source independent review parallelization instance, ja: three-source independent review parallelization 实例 }
    scenario_id: null
    descriptions:
      zh: independent-source-review@2 启动 regulation、official-docs、paper 三个 ParallelBranch，max_concurrency=3，all-settled 后 fan-in。
      en: independent-source-review@2 launches regulation, official-docs, and paper ParallelBranches with max_concurrency=3 and all-settled fan-in.
      ja: independent-source-review@2 は三 ParallelBranch を max_concurrency=3/all-settled fan-in で起動します。
    field_values:
      composition_specification_id: independent-source-review
      version: "2"
      valid_from: 2026-07-16T00:00:00Z
      control_shape: fan-out-fan-in
      join_policy: all-settled
      branch_refs: [regulation-branch, official-docs-branch, paper-branch]
      independence_condition: branches do not read one another's intermediate state
      launch_semantics: launch all ready branches as one bounded fan-out
      max_concurrency: 3
    related_node_ids: [Parallelization, CompositionPattern, ParallelBranch]
    related_relation_ids: [Parallelization-is_a-CompositionPattern]
    expected_result: { zh: 接受为完整 Parallelization 模式实例。, en: Accept as complete Parallelization pattern instance., ja: 完全 Parallelization pattern 实例として受理。 }
    why_valid_or_invalid:
      zh: 字段与正例一致，体现 LangGraph parallel branch 工作流模式而非单次运行。
      en: Fields match positive case reflecting LangGraph parallel branch workflow pattern not a single run.
      ja: 正例 field と一致し LangGraph parallel branch workflow pattern を示します。
    synthetic: true
    verified_version: null
    source_claims: [claim-parallelization-001, claim-parallelization-hierarchy]
'@

}

foreach ($kv in $p.GetEnumerator()) {
    Insert-Examples -RelPath $kv.Key -Block $kv.Value
}

Write-Host "Applied $($p.Count) composition patches"
