# Source catalogs and description generators for plane example upgrades.
# ASCII-safe strings for Windows PowerShell 5.x compatibility.

function New-KindTemplates {
    param($Positive, $Boundary, $Counter, $Instance)
    return @{
        positive = $Positive
        boundary = $Boundary
        counterexample = $Counter
        instance = $Instance
    }
}

function Expand-Desc {
    param([scriptblock]$Block, [string]$NodeId)
    $r = & $Block $NodeId
    return @{ zh = $r.zh; en = $r.en; ja = $r.ja }
}

function Get-PlaneDescription {
    param([string]$SourceId, [string]$NodeId, [string]$Kind, [hashtable]$Catalog)
    $templates = $Catalog.Templates[$SourceId]
    if (-not $templates) { throw "Unknown source: $SourceId" }
    $kindKey = if ($templates.ContainsKey($Kind)) { $Kind } else { 'positive' }
    $tpl = $templates[$kindKey]
    return Expand-Desc -Block $tpl -NodeId $NodeId
}

function T {
    param([string]$NodeId, [string]$Zh, [string]$En, [string]$Ja)
    return @{ zh = ($Zh -replace '\{n\}', $NodeId); en = ($En -replace '\{n\}', $NodeId); ja = ($Ja -replace '\{n\}', $NodeId) }
}

# --- Feedback plane ---
$Script:FeedbackCatalog = @{
    SourceIds = @('instructgpt','dpo','self_refine','reflexion','constitutional_ai','chatbot_arena','agentbench','swe_bench','openai_evals','ragas','braintrust','wandb','dspy_optimizers')
    DefaultModuleKey = 'feedback-plane'
    DefaultSources = @('instructgpt','ragas','agentbench','openai_evals')
    NodeSourceMap = @{
        LearningSignal = @('instructgpt','dpo','reflexion','dspy_optimizers')
        PreferenceExample = @('instructgpt','dpo','dspy_optimizers')
        RewardModelScore = @('instructgpt','dpo','dspy_optimizers')
        ChangeProposal = @('dpo','self_refine','dspy_optimizers')
        Feedback = @('self_refine','reflexion','constitutional_ai')
        HumanFeedback = @('instructgpt','constitutional_ai','chatbot_arena')
        RevisionArtifact = @('self_refine','reflexion','constitutional_ai')
        EvaluationRun = @('self_refine','openai_evals','ragas','agentbench')
        Score = @('chatbot_arena','ragas','braintrust','wandb')
        Verdict = @('chatbot_arena','agentbench','swe_bench')
        EvaluationScenario = @('chatbot_arena','agentbench','swe_bench')
        Rubric = @('constitutional_ai','openai_evals','agentbench')
        EvaluationCriterion = @('openai_evals','braintrust','constitutional_ai')
        EvaluationMetric = @('ragas','wandb','braintrust')
        EvaluationCostMetric = @('wandb','ragas','openai_evals')
        EvaluationSpecification = @('openai_evals','agentbench','swe_bench')
    }
    ModuleSourceMap = @{
        'feedback-metrics-evaluation' = @('chatbot_arena','ragas','openai_evals','swe_bench')
        'feedback-optimization-learning' = @('instructgpt','dpo','dspy_optimizers','reflexion')
        'feedback-review-optimization' = @('self_refine','reflexion','constitutional_ai')
        'feedback-plane' = @('instructgpt','ragas','agentbench','openai_evals')
    }
    Templates = @{
        instructgpt = (New-KindTemplates { param($n) T $n 'InstructGPT (Ouyang et al., 2022) RLHF: SFT -> human-ranked RM r_theta(x,y) -> PPO; ~13k demos + 33k comparisons; {n} maps supervised/preference data-prep boundary.' 'InstructGPT (Ouyang et al., 2022) RLHF: SFT -> human-ranked RM r_theta(x,y) -> PPO; ~13k demos + 33k comparisons; {n} maps supervised/preference data-prep boundary.' 'InstructGPT SFT->RM->PPO; {n} data prep boundary.' } { param($n) T $n 'InstructGPT comparisons train RM; PPO uses RM scores; {n} must not mix RewardModelScore or Verdict as training signal.' 'InstructGPT comparisons train RM; PPO uses RM scores; {n} must not mix RewardModelScore or Verdict as training signal.' 'InstructGPT RM/PPO boundary; {n} not Score/Verdict.' } { param($n) T $n 'Raw demonstration without dataset_ref/transformation_policy_ref cannot serve as InstructGPT-style {n}.' 'Raw demonstration without dataset_ref/transformation_policy_ref cannot serve as InstructGPT-style {n}.' 'Missing dataset_ref rejects InstructGPT-style {n}.' } { param($n) T $n 'InstructGPT instance: prompt->demonstration->dataset:instructgpt-sft-13k->{n} learning_objective=supervised.' 'InstructGPT instance: prompt->demonstration->dataset:instructgpt-sft-13k->{n} learning_objective=supervised.' 'InstructGPT instance maps to {n}.' })
        dpo = (New-KindTemplates { param($n) T $n 'DPO (Rafailov et al., 2023) L_DPO = -E[log sigmoid(beta*(log pi(y_w|x)/pi_ref(y_w|x) - log pi(y_l|x)/pi_ref(y_l|x)))]; TRL DPOTrainer prompt/chosen/rejected; {n} retains preference records not training batches.' 'DPO (Rafailov et al., 2023) L_DPO loss; TRL DPOTrainer prompt/chosen/rejected; {n} retains preference records not training batches.' 'DPO L_DPO; prompt/chosen/rejected; {n} not training batch.' } { param($n) T $n 'DPO requires learning_objective=preference; cannot auto-convert 1-5 Score to chosen/rejected for {n}.' 'DPO requires learning_objective=preference; cannot auto-convert 1-5 Score to chosen/rejected for {n}.' 'DPO preference objective required.' } { param($n) T $n 'Chosen-only click logs cannot serve as DPO-style {n}.' 'Chosen-only click logs cannot serve as DPO-style {n}.' 'Missing rejected rejects DPO-style {n}.' } { param($n) T $n 'DPO instance: prompt/chosen/rejected->dataset:help-dpo-v2->{n}.' 'DPO instance: prompt/chosen/rejected->dataset:help-dpo-v2->{n}.' 'DPO instance maps to {n}.' })
        self_refine = (New-KindTemplates { param($n) T $n 'Self-Refine (Madaan et al., 2023) Generate->Feedback->Refine loop without external training; {n} maps feedback-driven revision artifacts.' 'Self-Refine (Madaan et al., 2023) Generate->Feedback->Refine loop without external training; {n} maps feedback-driven revision artifacts.' 'Self-Refine Generate->Feedback->Refine; {n} revision artifact.' } { param($n) T $n 'Self-Refine feedback is runtime self-critique; separate {n} from Verdict.' 'Self-Refine feedback is runtime self-critique; separate {n} from Verdict.' 'Self-Refine feedback not Verdict.' } { param($n) T $n 'Single generation without Feedback round is not Self-Refine-style {n}.' 'Single generation without Feedback round is not Self-Refine-style {n}.' 'No Feedback round rejects Self-Refine-style {n}.' } { param($n) T $n 'Self-Refine instance: draft_v1->feedback->revision_v2->{n}.' 'Self-Refine instance: draft_v1->feedback->revision_v2->{n}.' 'Self-Refine instance maps to {n}.' })
        reflexion = (New-KindTemplates { param($n) T $n 'Reflexion (Shinn et al., 2023) reflect(trajectory, task_description)->memory.append->retry; {n} maps reflection-style LearningSignal/Feedback.' 'Reflexion (Shinn et al., 2023) reflect(trajectory)->memory.append->retry; {n} maps reflection-style LearningSignal/Feedback.' 'Reflexion reflect->memory->retry; {n} reflection signal.' } { param($n) T $n 'Reflexion reflection goes to memory not RewardModelScore; distinguish {n} from Score.' 'Reflexion reflection goes to memory not RewardModelScore; distinguish {n} from Score.' 'Reflexion reflection not Score.' } { param($n) T $n 'Retry without reflect(trajectory) is not Reflexion-style {n}.' 'Retry without reflect(trajectory) is not Reflexion-style {n}.' 'No reflect rejects Reflexion-style {n}.' } { param($n) T $n 'Reflexion instance: failed->reflect->retry->{n} Feedback mode=reflection.' 'Reflexion instance: failed->reflect->retry->{n} Feedback mode=reflection.' 'Reflexion instance maps to {n}.' })
        constitutional_ai = (New-KindTemplates { param($n) T $n 'Constitutional AI (Bai et al., 2022) RLAIF: self-critique/revise->AI preference pairs; {n} maps principle-driven Rubric/Feedback.' 'Constitutional AI (Bai et al., 2022) RLAIF: self-critique/revise->AI preference pairs; {n} maps principle-driven Rubric/Feedback.' 'Constitutional AI RLAIF; {n} principle Rubric.' } { param($n) T $n 'CAI principles are Rubric spec; revision is Feedback event; separate {n} spec from training.' 'CAI principles are Rubric spec; revision is Feedback event; separate {n} spec from training.' 'CAI principles spec; revision event.' } { param($n) T $n 'Vague scoring without constitutional principles cannot serve as CAI-style {n}.' 'Vague scoring without constitutional principles cannot serve as CAI-style {n}.' 'Missing principles rejects CAI-style {n}.' } { param($n) T $n 'CAI instance: principle->self-critique->revised->{n} origin_kind=ai-assisted.' 'CAI instance: principle->self-critique->revised->{n} origin_kind=ai-assisted.' 'CAI instance maps to {n}.' })
        chatbot_arena = (New-KindTemplates { param($n) T $n 'LMSYS Chatbot Arena (Zheng et al., 2023): MT-Bench 80 items GPT-4 judge 1-10; Arena pairwise + Elo; {n} maps EvaluationRun/Score/Verdict.' 'LMSYS Chatbot Arena (Zheng et al., 2023): MT-Bench 80 items GPT-4 judge 1-10; Arena pairwise + Elo; {n} maps EvaluationRun/Score/Verdict.' 'Chatbot Arena MT-Bench+Elo; {n} eval evidence.' } { param($n) T $n 'MT-Bench Score is judge output; Rubric is scale; {n} must not treat Elo table as single Verdict.' 'MT-Bench Score is judge output; Rubric is scale; {n} must not treat Elo table as single Verdict.' 'Elo table not single Verdict.' } { param($n) T $n 'Missing model_a/model_b pairing cannot serve as Arena-style {n}.' 'Missing model_a/model_b pairing cannot serve as Arena-style {n}.' 'Missing pairwise rejects Arena-style {n}.' } { param($n) T $n 'Arena instance: model_a vs model_b->judge picks A->Elo delta->{n} Verdict outcome=preferred_a.' 'Arena instance: model_a vs model_b->judge picks A->Elo delta->{n} Verdict outcome=preferred_a.' 'Arena instance maps to {n} Verdict.' })
        agentbench = (New-KindTemplates { param($n) T $n 'AgentBench (Liu et al., 2023) 8 envs OS/DB/KG/Web Shopping etc.; {n} maps EvaluationScenario/Run/Rubric.' 'AgentBench (Liu et al., 2023) 8 envs OS/DB/KG/Web Shopping etc.; {n} maps EvaluationScenario/Run/Rubric.' 'AgentBench 8 envs; {n} scenario/run.' } { param($n) T $n 'AgentBench success_rate is aggregate; {n} records one run not leaderboard.' 'AgentBench success_rate is aggregate; {n} records one run not leaderboard.' 'Leaderboard not single run.' } { param($n) T $n 'Missing environment_id cannot serve as AgentBench-style {n}.' 'Missing environment_id cannot serve as AgentBench-style {n}.' 'Missing environment_id rejects AgentBench-style {n}.' } { param($n) T $n 'AgentBench instance: env=web_shopping task_id=ws-042->{n} EvaluationRun.' 'AgentBench instance: env=web_shopping task_id=ws-042->{n} EvaluationRun.' 'AgentBench instance maps to {n} Run.' })
        swe_bench = (New-KindTemplates { param($n) T $n 'SWE-bench (Jimenez et al., 2024) 2294 GitHub issues+PRs; resolved rate (%) tests patch against repo tests; {n} maps code-fix evaluation.' 'SWE-bench (Jimenez et al., 2024) 2294 GitHub issues+PRs; resolved rate (%) tests patch against repo tests; {n} maps code-fix evaluation.' 'SWE-bench resolved rate; {n} code-fix eval.' } { param($n) T $n 'SWE-bench resolved is Score; Rubric defines pass criteria; {n} must not treat issue title as Verdict.' 'SWE-bench resolved is Score; Rubric defines pass criteria; {n} must not treat issue title as Verdict.' 'Issue title not Verdict.' } { param($n) T $n 'Diff without repo/commit/test_log_ref cannot serve as SWE-bench-style {n}.' 'Diff without repo/commit/test_log_ref cannot serve as SWE-bench-style {n}.' 'Missing repo/commit rejects SWE-bench-style {n}.' } { param($n) T $n 'SWE-bench instance: django__django-11099->tests passed->resolved=true->{n} Score.' 'SWE-bench instance: django__django-11099->tests passed->resolved=true->{n} Score.' 'SWE-bench instance maps to {n} Score.' })
        openai_evals = (New-KindTemplates { param($n) T $n 'OpenAI Evals client.evals.create(name, data_source_config, testing_criteria=[string_check, model_graded, text_similarity]); {n} maps EvaluationRun/Criterion/Rubric/Score.' 'OpenAI Evals client.evals.create with testing_criteria string_check/model_graded/text_similarity; {n} maps EvaluationRun/Criterion/Rubric/Score.' 'OpenAI Evals create+graders; {n} eval config.' } { param($n) T $n 'testing_criteria is spec; run output is Score; {n} must separate config from run results.' 'testing_criteria is spec; run output is Score; {n} must separate config from run results.' 'Criteria spec; run output Score.' } { param($n) T $n 'Ad-hoc script without testing_criteria cannot serve as OpenAI Evals-style {n}.' 'Ad-hoc script without testing_criteria cannot serve as OpenAI Evals-style {n}.' 'Missing criteria rejects OpenAI Evals-style {n}.' } { param($n) T $n 'OpenAI Evals instance: string_check eq Hardware->run completed->{n} eval_id=it-ticket-v1.' 'OpenAI Evals instance: string_check eq Hardware->run completed->{n} eval_id=it-ticket-v1.' 'OpenAI Evals instance maps to {n} Run.' })
        ragas = (New-KindTemplates { param($n) T $n 'RAGAS from ragas.metrics import faithfulness, context_precision, answer_relevancy; evaluate(dataset, metrics=[...]); {n} maps RAG quality EvaluationMetric/Score/Run.' 'RAGAS faithfulness/context_precision/answer_relevancy; evaluate(dataset, metrics=[...]); {n} maps RAG quality EvaluationMetric/Score/Run.' 'RAGAS faithfulness/context_precision; {n} RAG metric.' } { param($n) T $n 'faithfulness measures grounding; latency is cost; {n} must not treat wall-clock as faithfulness.' 'faithfulness measures grounding; latency is cost; {n} must not treat wall-clock as faithfulness.' 'Latency not faithfulness.' } { param($n) T $n 'Missing retrieved_contexts cannot run RAGAS-style {n} context_precision.' 'Missing retrieved_contexts cannot run RAGAS-style {n} context_precision.' 'Missing retrieved_contexts rejects RAGAS-style {n}.' } { param($n) T $n 'RAGAS instance: faithfulness=0.87->{n} Score metric_id=ragas-faithfulness.' 'RAGAS instance: faithfulness=0.87->{n} Score metric_id=ragas-faithfulness.' 'RAGAS instance maps to {n} Score.' })
        braintrust = (New-KindTemplates { param($n) T $n 'Braintrust Eval(''my-project'', data=dataset, task=my_task, scores=[Factuality]); {n} maps EvaluationRun/Score/EvaluationCriterion.' 'Braintrust Eval(''my-project'', data, task, scores=[Factuality]); {n} maps EvaluationRun/Score/EvaluationCriterion.' 'Braintrust Eval; {n} eval run.' } { param($n) T $n 'Braintrust scores are scorer output; Criterion is pass/fail rule; {n} must not treat project config as Verdict.' 'Braintrust scores are scorer output; Criterion is pass/fail rule; {n} must not treat project config as Verdict.' 'Project config not Verdict.' } { param($n) T $n 'JSON without task/scores cannot serve as Braintrust-style {n}.' 'JSON without task/scores cannot serve as Braintrust-style {n}.' 'Missing task/scores rejects Braintrust-style {n}.' } { param($n) T $n 'Braintrust instance: Factuality=0.92->{n} Score scorer=Factuality.' 'Braintrust instance: Factuality=0.92->{n} Score scorer=Factuality.' 'Braintrust instance maps to {n} Score.' })
        wandb = (New-KindTemplates { param($n) T $n 'W&B wandb.init(project=''agent-eval''); wandb.log({''accuracy'':0.95,''latency'':1.2}); {n} maps EvaluationMetric/Score/EvaluationCostMetric.' 'W&B wandb.init(project=''agent-eval''); wandb.log({''accuracy'':0.95,''latency'':1.2}); {n} maps EvaluationMetric/Score/EvaluationCostMetric.' 'W&B wandb.log accuracy/latency; {n} eval telemetry.' } { param($n) T $n 'latency is EvaluationCostMetric; accuracy is Score; {n} must state metric_kind.' 'latency is EvaluationCostMetric; accuracy is Score; {n} must state metric_kind.' 'Latency cost; accuracy Score.' } { param($n) T $n 'Print without run_id/project cannot serve as W&B-style {n}.' 'Print without run_id/project cannot serve as W&B-style {n}.' 'Missing run_id rejects W&B-style {n}.' } { param($n) T $n 'W&B instance: eval_cost_usd=0.042 tokens=1500->{n} EvaluationCostMetric.' 'W&B instance: eval_cost_usd=0.042 tokens=1500->{n} EvaluationCostMetric.' 'W&B instance maps to {n} CostMetric.' })
        dspy_optimizers = (New-KindTemplates { param($n) T $n 'DSPy BootstrapFewShotWithRandomSearch(metric, max_bootstrapped_demos=4)->teleprompter.compile(RAG(), trainset); {n} maps ChangeProposal/LearningSignal/RewardModelScore optimization proposals.' 'DSPy BootstrapFewShotWithRandomSearch->teleprompter.compile(RAG(), trainset); {n} maps ChangeProposal/LearningSignal/RewardModelScore optimization proposals.' 'DSPy BootstrapFewShot->compile(RAG); {n} optimization proposal.' } { param($n) T $n 'compiled program is artifact; ChangeProposal is pending change; {n} records proposal boundary.' 'compiled program is artifact; ChangeProposal is pending change; {n} records proposal boundary.' 'Compiled artifact; Proposal pending.' } { param($n) T $n 'compile() without metric/trainset cannot serve as DSPy-style {n} ChangeProposal.' 'compile() without metric/trainset cannot serve as DSPy-style {n} ChangeProposal.' 'Missing metric/trainset rejects DSPy-style {n}.' } { param($n) T $n 'DSPy instance: compiled demos=4->proposal_id=prompt-opt-v3->{n} ChangeProposal.' 'DSPy instance: compiled demos=4->proposal_id=prompt-opt-v3->{n} ChangeProposal.' 'DSPy instance maps to {n} ChangeProposal.' })
    }
}

# --- Runtime plane ---
$Script:RuntimeCatalog = @{
    SourceIds = @('w3c_prov','opentelemetry','langsmith','langfuse','arize_phoenix','helicone','vllm','ollama')
    DefaultModuleKey = 'runtime-plane'
    DefaultSources = @('w3c_prov','opentelemetry','langsmith','langfuse')
    NodeSourceMap = @{
        TraceSpan = @('opentelemetry','langsmith','langfuse')
        TraceRecord = @('langsmith','langfuse','helicone','opentelemetry')
        TraceEvent = @('opentelemetry','langfuse','arize_phoenix')
        ObservabilityEvent = @('opentelemetry','langfuse','arize_phoenix')
        Execution = @('w3c_prov','opentelemetry','helicone','langsmith')
        RuntimeEnvironment = @('vllm','ollama','w3c_prov')
        GenerativeModel = @('vllm','ollama','helicone')
        ModelActor = @('vllm','ollama','helicone')
        ObservableSummary = @('arize_phoenix','opentelemetry','helicone')
        Checkpoint = @('w3c_prov','langsmith','opentelemetry')
        Artifact = @('w3c_prov','opentelemetry','langsmith')
    }
    ModuleSourceMap = @{
        'runtime-observability' = @('opentelemetry','langsmith','langfuse','arize_phoenix')
        'runtime-execution-attempts' = @('w3c_prov','opentelemetry','helicone','langsmith')
        'runtime-system' = @('vllm','ollama','w3c_prov','opentelemetry')
        'runtime-actors' = @('w3c_prov','vllm','ollama','helicone')
        'runtime-artifacts' = @('w3c_prov','opentelemetry','langsmith')
        'runtime-plane' = @('w3c_prov','opentelemetry','langsmith','langfuse')
    }
    Templates = @{
        w3c_prov = (New-KindTemplates { param($n) T $n 'W3C PROV-O prov:Agent wasAssociatedWith prov:Activity; Activity used/generated Entity; {n} maps actor/execution/artifact provenance graph.' 'W3C PROV-O prov:Agent wasAssociatedWith Activity; Activity used/generated Entity; {n} maps actor/execution/artifact provenance graph.' 'PROV-O Agent-Activity-Entity; {n} provenance graph.' } { param($n) T $n 'PROV Entity is stable content; Activity is bounded execution; {n} must not treat span preview as Entity.' 'PROV Entity is stable content; Activity is bounded execution; {n} must not treat span preview as Entity.' 'Span preview not Entity.' } { param($n) T $n 'ID without PROV relations cannot serve as PROV-O-style {n}.' 'ID without PROV relations cannot serve as PROV-O-style {n}.' 'Missing PROV relations rejects {n}.' } { param($n) T $n 'PROV-O instance: Agent wasAssociatedWith Activity used Entity->{n}.' 'PROV-O instance: Agent wasAssociatedWith Activity used Entity->{n}.' 'PROV-O instance maps to {n}.' })
        opentelemetry = (New-KindTemplates { param($n) T $n 'OpenTelemetry TracerProvider->Tracer->Span; tracer.start_span(''llm.call'', attributes={model:gpt-4,tokens:1500}); SpanKind CLIENT/SERVER/INTERNAL; {n} maps TraceSpan/TraceRecord/ObservabilityEvent.' 'OpenTelemetry Tracer->Span; tracer.start_span(''llm.call'', attributes={model:gpt-4,tokens:1500}); SpanKind CLIENT/SERVER/INTERNAL; {n} maps TraceSpan/TraceRecord/ObservabilityEvent.' 'OTel Tracer->Span llm.call; {n} TraceSpan/Record.' } { param($n) T $n 'Span.add_event produces TraceEvent on Span; Metrics are not Execution; {n} preserves boundaries.' 'Span.add_event produces TraceEvent on Span; Metrics are not Execution; {n} preserves boundaries.' 'OTel Event on Span; Metrics not Execution.' } { param($n) T $n 'Log without trace_id/span_id cannot serve as OTel-style {n} TraceSpan.' 'Log without trace_id/span_id cannot serve as OTel-style {n} TraceSpan.' 'Missing trace_id rejects OTel-style {n}.' } { param($n) T $n 'OTel instance: trace_id=4bf92f3577b34da6 span_id=00f067aa kind=CLIENT name=llm.call->{n}.' 'OTel instance: trace_id+span_id kind=CLIENT name=llm.call->{n}.' 'OTel instance maps to {n}.' })
        langsmith = (New-KindTemplates { param($n) T $n 'LangSmith RunTree parent_run_id, run_type chain/llm/tool; tracing_v2_enabled(project_name) chain.invoke(); {n} maps TraceRecord/TraceSpan/Execution.' 'LangSmith RunTree parent_run_id, run_type chain/llm/tool; tracing_v2_enabled chain.invoke(); {n} maps TraceRecord/TraceSpan/Execution.' 'LangSmith RunTree parent_run_id run_type; {n} run tree.' } { param($n) T $n 'run.outputs is trace preview not PROV Entity; {n} must not treat run JSON as Artifact digest.' 'run.outputs is trace preview not PROV Entity; {n} must not treat run JSON as Artifact digest.' 'run.outputs not Artifact.' } { param($n) T $n 'Log without parent_run_id/run_type cannot serve as LangSmith-style {n}.' 'Log without parent_run_id/run_type cannot serve as LangSmith-style {n}.' 'Missing parent_run_id rejects LangSmith-style {n}.' } { param($n) T $n 'LangSmith instance: run_id=0192a3b4 parent_run_id=0192a3b3 run_type=llm->{n}.' 'LangSmith instance: run_id parent_run_id run_type=llm->{n}.' 'LangSmith instance maps to {n}.' })
        langfuse = (New-KindTemplates { param($n) T $n 'Langfuse trace=langfuse.trace(name=''my-agent''); span=trace.span(name=''llm-call'', metadata={model:gpt-4}); trace.score(name=''accuracy'', value=0.95); {n} maps TraceRecord/TraceSpan/ObservabilityEvent.' 'Langfuse trace.span metadata model=gpt-4; trace.score accuracy=0.95; {n} maps TraceRecord/TraceSpan/ObservabilityEvent.' 'Langfuse trace.span+score; {n} TraceRecord/Span.' } { param($n) T $n 'Langfuse score is eval signal not Execution; {n} preserves trace/span/score distinction.' 'Langfuse score is eval signal not Execution; {n} preserves trace/span/score distinction.' 'score not Execution.' } { param($n) T $n 'Generation without trace container cannot serve as Langfuse-style {n} TraceRecord.' 'Generation without trace container cannot serve as Langfuse-style {n} TraceRecord.' 'Missing trace rejects Langfuse-style {n}.' } { param($n) T $n 'Langfuse instance: trace_id=langfuse-0192a3b4 span llm-call score accuracy=0.95->{n}.' 'Langfuse instance: trace+span+score->{n}.' 'Langfuse instance maps to {n}.' })
        arize_phoenix = (New-KindTemplates { param($n) T $n 'Arize Phoenix embedding drift, prompt/response quality, trace viz; {n} maps ObservabilityEvent/MetricSample.' 'Arize Phoenix embedding drift, prompt/response quality, trace viz; {n} maps ObservabilityEvent/MetricSample.' 'Phoenix drift+quality; {n} ObservabilityEvent.' } { param($n) T $n 'p99 latency is ObservableSummary; single span is TraceSpan; {n} must not treat percentile as Execution.' 'p99 latency is ObservableSummary; single span is TraceSpan; {n} must not treat percentile as Execution.' 'p99 aggregate; single span TraceSpan.' } { param($n) T $n 'Latency without embedding_version cannot serve as Phoenix-style {n} drift event.' 'Latency without embedding_version cannot serve as Phoenix-style {n} drift event.' 'Missing embedding_version rejects Phoenix-style {n}.' } { param($n) T $n 'Phoenix instance: embedding_drift_score=0.18 prompt_quality=0.91->{n} ObservabilityEvent.' 'Phoenix instance: drift+quality->{n} ObservabilityEvent.' 'Phoenix instance maps to {n} Event.' })
        helicone = (New-KindTemplates { param($n) T $n 'Helicone LLM proxy replaces base_url to trace API; records latency/cost/model/tokens; {n} maps TraceRecord/Execution/CostMetric.' 'Helicone LLM proxy replaces base_url to trace API; records latency/cost/model/tokens; {n} maps TraceRecord/Execution/CostMetric.' 'Helicone base_url proxy trace; {n} telemetry.' } { param($n) T $n 'cost_usd is cost metric; Execution is bounded run; {n} must not treat proxy log as completed PROV Activity.' 'cost_usd is cost metric; Execution is bounded run; {n} must not treat proxy log as completed PROV Activity.' 'cost metric; not completed Activity.' } { param($n) T $n 'Mock bypassing Helicone gateway cannot serve as Helicone-style {n}.' 'Mock bypassing Helicone gateway cannot serve as Helicone-style {n}.' 'Gateway bypass rejects Helicone-style {n}.' } { param($n) T $n 'Helicone instance: request_id=hc-771 latency_ms=842 cost_usd=0.003 model=gpt-4o->{n}.' 'Helicone instance: request_id latency cost model->{n}.' 'Helicone instance maps to {n} Execution.' })
        vllm = (New-KindTemplates { param($n) T $n 'vLLM python -m vllm.entrypoints.openai.api_server --model meta-llama/Llama-3-8B; PagedAttention+continuous batching; {n} maps RuntimeEnvironment/Execution/GenerativeModel.' 'vLLM api_server --model meta-llama/Llama-3-8B; PagedAttention+continuous batching; {n} maps RuntimeEnvironment/Execution/GenerativeModel.' 'vLLM api_server PagedAttention; {n} serving env.' } { param($n) T $n 'batch scheduler is env state; POST /v1/chat/completions is Execution; {n} preserves env/execution boundary.' 'batch scheduler is env state; POST /v1/chat/completions is Execution; {n} preserves env/execution boundary.' 'scheduler env; API call Execution.' } { param($n) T $n 'Script without model/endpoint cannot serve as vLLM-style {n} RuntimeEnvironment.' 'Script without model/endpoint cannot serve as vLLM-style {n} RuntimeEnvironment.' 'Missing model/endpoint rejects vLLM-style {n}.' } { param($n) T $n 'vLLM instance: env_id=vllm-llama3-8b endpoint=http://127.0.0.1:8000/v1->{n}.' 'vLLM instance: env_id endpoint model->{n} RuntimeEnvironment.' 'vLLM instance maps to {n} RuntimeEnvironment.' })
        ollama = (New-KindTemplates { param($n) T $n 'Ollama ollama run llama3 / ollama serve; POST /api/chat {model:llama3,messages:[...]}; {n} maps RuntimeEnvironment/LocalExecution/ModelActor.' 'Ollama ollama serve; POST /api/chat {model:llama3,messages}; {n} maps RuntimeEnvironment/LocalExecution/ModelActor.' 'Ollama /api/chat model=llama3; {n} local runtime.' } { param($n) T $n 'model manifest is env config; chat completion is Execution; {n} must not treat Modelfile path as Execution result.' 'model manifest is env config; chat completion is Execution; {n} must not treat Modelfile path as Execution result.' 'manifest env; chat completion Execution.' } { param($n) T $n 'Echo without model/messages cannot serve as Ollama-style {n} Execution.' 'Echo without model/messages cannot serve as Ollama-style {n} Execution.' 'Missing model/messages rejects Ollama-style {n}.' } { param($n) T $n 'Ollama instance: POST /api/chat model=llama3->{n} execution_id=ollama-chat-12.' 'Ollama instance: POST /api/chat model=llama3->{n} execution_id=ollama-chat-12.' 'Ollama instance maps to {n} Execution.' })
    }
}

# --- Info plane ---
$Script:InfoCatalog = @{
    SourceIds = @('attention','outlines','vercel_ai_sdk','instructor','perplexity','claude_citations','dspy_signatures')
    DefaultModuleKey = 'info-plane'
    DefaultSources = @('attention','vercel_ai_sdk','claude_citations','dspy_signatures')
    NodeSourceMap = @{
        ContentPart = @('attention','vercel_ai_sdk','claude_citations')
        TextContent = @('attention','vercel_ai_sdk','perplexity')
        StructuredData = @('instructor','outlines','dspy_signatures')
        StructuredDataBlock = @('instructor','outlines','dspy_signatures')
        SourceReference = @('perplexity','claude_citations','attention')
        CitationAnchor = @('perplexity','claude_citations','attention')
        ContentAnchor = @('claude_citations','perplexity','attention')
        SourceProvenance = @('claude_citations','perplexity','attention')
        OutputCitation = @('perplexity','claude_citations','attention')
        PromptTemplate = @('dspy_signatures','instructor','vercel_ai_sdk')
        SystemInstruction = @('dspy_signatures','instructor','attention')
        PromptArgument = @('dspy_signatures','instructor','vercel_ai_sdk')
        OutputSegment = @('vercel_ai_sdk','attention','outlines')
        StandardOutput = @('vercel_ai_sdk','attention','outlines')
        MessageHistory = @('attention','vercel_ai_sdk','claude_citations')
        AssistantMessage = @('vercel_ai_sdk','instructor','attention')
    }
    ModuleSourceMap = @{
        'info-prompts-instructions' = @('dspy_signatures','instructor','vercel_ai_sdk','attention')
        'info-storage-sources' = @('perplexity','claude_citations','attention')
        'info-output-disclosure' = @('vercel_ai_sdk','perplexity','claude_citations')
        'info-content-parts' = @('attention','instructor','outlines')
        'info-content-block-modality' = @('attention','outlines','instructor')
        'info-container-command' = @('vercel_ai_sdk','outlines','attention')
        'info-messages-instructions' = @('attention','vercel_ai_sdk','claude_citations')
        'info-indexing' = @('perplexity','attention','dspy_signatures')
        'info-plane' = @('attention','vercel_ai_sdk','claude_citations','dspy_signatures')
    }
    Templates = @{
        attention = (New-KindTemplates { param($n) T $n 'Attention Is All You Need (Vaswani et al., 2017) self-attention Q/K/V scaled dot-product; context window is transformer sequence foundation; {n} maps ContentPart/token boundaries.' 'Attention Is All You Need (Vaswani et al., 2017) self-attention Q/K/V; context window is transformer sequence foundation; {n} maps ContentPart/token boundaries.' 'Attention self-attention Q/K/V; {n} context/token boundary.' } { param($n) T $n 'context length is model constraint; {n} records info structure; KV cache is not SourceReference.' 'context length is model constraint; {n} records info structure; KV cache is not SourceReference.' 'KV cache not SourceReference.' } { param($n) T $n 'Bare text without sequence_index/token boundary cannot serve as attention-style {n}.' 'Bare text without sequence_index/token boundary cannot serve as attention-style {n}.' 'Missing boundary rejects attention-style {n}.' } { param($n) T $n 'Attention instance: max_context_tokens=8192 sequence_index=42->{n} addressable segment.' 'Attention instance: max_context_tokens=8192 sequence_index=42->{n} addressable segment.' 'Attention instance maps to {n}.' })
        outlines = (New-KindTemplates { param($n) T $n 'Outlines (Willard & Louf, 2023) FSM: model.generate(prompt, regex=r''\d{3}-\d{2}-\d{4}'') or JSON schema; {n} maps StructuredContent/OutputFormat.' 'Outlines (Willard & Louf, 2023) FSM regex or JSON schema; {n} maps StructuredContent/OutputFormat.' 'Outlines FSM/regex; {n} StructuredContent.' } { param($n) T $n 'Outlines constraint is OutputFormat spec; unvalidated JSON is not StructuredData; {n} preserves spec/wire boundary.' 'Outlines constraint is OutputFormat spec; unvalidated JSON is not StructuredData; {n} preserves spec/wire boundary.' 'Unvalidated JSON not StructuredData.' } { param($n) T $n 'Free text without schema/regex cannot serve as Outlines-style {n} StructuredData.' 'Free text without schema/regex cannot serve as Outlines-style {n} StructuredData.' 'Missing schema/regex rejects Outlines-style {n}.' } { param($n) T $n 'Outlines instance: regex SSN validated output->{n} StructuredData schema_ref=ssn-regex-v1.' 'Outlines instance: regex SSN validated output->{n} StructuredData.' 'Outlines instance maps to {n} StructuredData.' })
        vercel_ai_sdk = (New-KindTemplates { param($n) T $n 'Vercel AI SDK streamText({model:openai(''gpt-4''),prompt})->textStream; for await chunk of textStream; {n} maps StreamingOutput/OutputRepresentation.' 'Vercel AI SDK streamText->textStream; for await chunk of textStream; {n} maps StreamingOutput/OutputRepresentation.' 'Vercel AI SDK streamText textStream chunk; {n} StreamingOutput.' } { param($n) T $n 'textStream chunk is OutputSegment event; complete AssistantMessage is terminal; {n} must not treat partial delta as final Message.' 'textStream chunk is OutputSegment event; complete AssistantMessage is terminal; {n} must not treat partial delta as final Message.' 'Partial delta not final Message.' } { param($n) T $n 'HTTP response without stream protocol/chunk index cannot serve as Vercel AI SDK-style {n} StreamingOutput.' 'HTTP response without stream protocol/chunk index cannot serve as Vercel AI SDK-style {n} StreamingOutput.' 'Missing chunk index rejects Vercel AI SDK-style {n}.' } { param($n) T $n 'Vercel AI SDK instance: stream chunks->{n} OutputSegment sequence_index=0,1.' 'Vercel AI SDK instance: stream chunks->{n} OutputSegment sequence_index=0,1.' 'Vercel AI SDK instance maps to {n} OutputSegment.' })
        instructor = (New-KindTemplates { param($n) T $n 'Instructor client=instructor.from_openai(OpenAI()); create(response_model=User, messages=[...]) Pydantic validation; {n} maps StructuredContent/OutputFormat type-safe parsing.' 'Instructor from_openai; create(response_model=User, messages) Pydantic validation; {n} maps StructuredContent/OutputFormat type-safe parsing.' 'Instructor response_model=User Pydantic; {n} StructuredContent.' } { param($n) T $n 'response_model is OutputFormat spec; raw JSON is wire; {n} records validated structured entity.' 'response_model is OutputFormat spec; raw JSON is wire; {n} records validated structured entity.' 'response_model spec; raw JSON wire.' } { param($n) T $n 'JSON without response_model/validation cannot serve as Instructor-style {n} StructuredData.' 'JSON without response_model/validation cannot serve as Instructor-style {n} StructuredData.' 'Missing response_model rejects Instructor-style {n}.' } { param($n) T $n 'Instructor instance: validated User->{n} StructuredData content_type=application/json.' 'Instructor instance: validated User->{n} StructuredData.' 'Instructor instance maps to {n} StructuredData.' })
        perplexity = (New-KindTemplates { param($n) T $n 'Perplexity inline [1] links to search results; citations[] url/snippet; {n} maps Citation/SourceReference clickable anchors.' 'Perplexity inline [1] links to search results; citations[] url/snippet; {n} maps Citation/SourceReference clickable anchors.' 'Perplexity [1]+citations url; {n} Citation/SourceReference.' } { param($n) T $n '[1] is CitationAnchor; full SourceReference needs url+digest; {n} must not treat hallucinated URL as verified source.' '[1] is CitationAnchor; full SourceReference needs url+digest; {n} must not treat hallucinated URL as verified source.' 'Hallucinated URL not verified source.' } { param($n) T $n '[1] without citations/url cannot serve as Perplexity-style {n} SourceReference.' '[1] without citations/url cannot serve as Perplexity-style {n} SourceReference.' 'Missing citations/url rejects Perplexity-style {n}.' } { param($n) T $n 'Perplexity instance: answer [1] citations url->{n} CitationAnchor index=1.' 'Perplexity instance: answer [1] citations url->{n} CitationAnchor index=1.' 'Perplexity instance maps to {n} CitationAnchor.' })
        claude_citations = (New-KindTemplates { param($n) T $n 'Claude Citations API citations=[{type:char_location, cited_text, document_index, start_char_index, end_char_index}]; supports document/URL/plain text; {n} maps Citation/ContentAnchor/SourceProvenance.' 'Claude Citations API char_location start/end_char_index document_index; {n} maps Citation/ContentAnchor/SourceProvenance.' 'Claude Citations char_location start/end; {n} ContentAnchor.' } { param($n) T $n 'char_location is ContentAnchor; SourceProvenance is attribution chain; {n} must not treat document_index alone as full SourceReference.' 'char_location is ContentAnchor; SourceProvenance is attribution chain; {n} must not treat document_index alone as full SourceReference.' 'document_index alone not full SourceReference.' } { param($n) T $n 'cited_text without start/end_char_index cannot serve as Claude Citations-style {n} ContentAnchor.' 'cited_text without start/end_char_index cannot serve as Claude Citations-style {n} ContentAnchor.' 'Missing char index rejects Claude Citations-style {n}.' } { param($n) T $n 'Claude Citations instance: char_location start=10 end=50 cited_text=self-attention->{n} ContentAnchor.' 'Claude Citations instance: char_location start/end cited_text->{n} ContentAnchor.' 'Claude Citations instance maps to {n} ContentAnchor.' })
        dspy_signatures = (New-KindTemplates { param($n) T $n 'DSPy Signatures ''context, question -> answer''; RAGAnswer(dspy.Signature) InputField/OutputField; {n} maps PromptTemplate/SystemInstruction/PromptVariable field contracts.' 'DSPy Signatures ''context, question -> answer''; RAGAnswer(dspy.Signature) InputField/OutputField; {n} maps PromptTemplate/SystemInstruction/PromptVariable field contracts.' 'DSPy Signature InputField/OutputField; {n} PromptTemplate.' } { param($n) T $n 'Signature is PromptTemplate spec; compiled prompt is runtime instance; {n} must not treat optimized demo as SystemInstruction authority.' 'Signature is PromptTemplate spec; compiled prompt is runtime instance; {n} must not treat optimized demo as SystemInstruction authority.' 'Signature spec; compiled prompt runtime.' } { param($n) T $n 'Ad-hoc prompt without InputField/OutputField cannot serve as DSPy-style {n} PromptTemplate.' 'Ad-hoc prompt without InputField/OutputField cannot serve as DSPy-style {n} PromptTemplate.' 'Missing InputField/OutputField rejects DSPy-style {n}.' } { param($n) T $n 'DSPy instance: Signature->PromptTemplate variable_names=[context, question]->{n}.' 'DSPy instance: Signature->PromptTemplate variable_names=[context, question]->{n}.' 'DSPy instance maps to {n} PromptTemplate.' })
    }
}
